<?php

/**
 * @file
 * Primary module hooks for Advanced permissions request module.
 */


 /**
 * Implements hook_form_FORM_ID_alter().
 */
function advanced_permissions_request_form_user_form_alter(&$form) {
    $userId = \Drupal::currentUser()->id();
    $mesage = "<a class='button button--primary' href=/user/" . $userId . "/request-roles>Request new roles</a>";
    $form['request_role'] = [
        '#type' => "markup",
        '#markup' => $mesage,
        '#weight' => -100,
    ];
}