# Schema for the configuration files of the Advanced permissions request module.
advanced_permissions_request.settings:
  type: config_object
  label: "Advanced permissions request settings"
  mapping:
    roles_to_offer:
      type: checkboxes
      label: "Please select what roles offer to users"
advanced_permissions_request.advanced_permissions_request_request_role:
  type: config_object
  label: "Request role form"
  mapping:
    message:
      type: radios
      label: "Now, you have this roles"
    roles:
      type: radios
      label: "Select one role"
    subjectemailaccept:
      type: textfield
      label: "Accept your request role"
    bodyemailaccept:
      type: textarea
      label: "Dear user, your request to update roles to was accept."
    subjectemaildenny:
      type: textfield
      label: "Dennied your request role"
    bodyemaildenny:
      type: textarea
      label: "Dear user, your request to update roles to was denied"
